### ISSUE TITLE
ネーミング、プロジェクション、エッジモーフ

### ISSUE THREAD

**Issue by nathanvasil** [LNSEAB/mmaccel#1]
Naming, PROJECTION, Edge Morphs

Thank you very much for MME.  I have enjoyed myself greatly creating effects for MMD.  I have discovered several issues with MME while developing effects.

I believe that several parameters used by MME are named incorrectly.  MaterialDiffuse and MaterialAmbient always return the same value.  In the English version of PMXE that I use, this is the "Diffuse" color of the model.  MaterialEmmisive returns a value corresponding to "Ambient" in the English version of PMXE that I use.

LightDiffuse always returns float3(0,0,0).  LightAmbient returns MMD's actual lighting values.  LightSpecular always returns values identical to LightAmbient.

float4x4 PROJECTION always returns an identity matrix.

Finally, it would be very useful to have something like MULTIPLYINGEDGE and ADDINGEDGE to access edge-related morphs.  It is difficult to create edge friendly effects without access to these parameters.

Thank you again for your hard work.  I hope that this information is of some use to you.  If you need me to create any effects demonstrating these issues, please let me know.

Google経由翻訳：

MMEのためにありがとうございました。私は非常にMMDのエフェクトを作成する自分自身を楽しんできました。効果を開発しながら、私はMMEでいくつかの問題を発見しました。

私は、MMEによって使用されるいくつかのパラメータが間違って命名されていると信じています。 MaterialDiffuseとMaterialAmbientは常に同じ値を返します。私が使用PMXEの英語版では、これはモデルの「Diffuse」色です。 MaterialEmmisiveは、私が使用PMXEの英語版では「Ambient」に対応する値を返します。

LightDiffuseは常にするfloat3（0,0,0）を返します。 LightAmbientはMMDの実際の照明値を返します。 LightSpecularは常にLightAmbientと同じ値を返します。

するfloat4x4 PROJECTIONは常に単位行列を返します。

最後に、エッジ関連のモーフにアクセスするためのMULTIPLYINGEDGEとADDINGEDGEのようなものを持っていることは非常に有用であろう。これらのパラメータにアクセスすることなく、エッジ優しい効果を作成することは困難です。

あなたのハードワークのためにありがとうございました。私はこの情報があなたにいくつかの使用であることを願っています。あなたは私がこれらの問題を実証する任意のエフェクトを作成する必要がある場合、私に知らせてください。

**Comment by LNSEAB** [comment]
Thank you for reporting your issue.
But, this repository is "MMAccel", not MME. I am not MME author.

**Comment by nathanvasil** [comment]
Oh excuse me!  I'm sorry, I thought there were MME release notes on your front page.  Please forgive me.


ああ、恐れ入ります！私は私があなたのフロントページ上のMMEのリリースノートがあると思っていました、申し訳ありません。 私を許してください。
